# dconf-branch: /org/gnome/desktop/notifications/
# Regenerate: gnome-settings-dump

[/]
application-children=['gnome-about-panel']
show-banners=false

[application/gnome-about-panel]
application-id='gnome-about-panel.desktop'
