# dconf-branch: /org/gnome/desktop/wm/preferences/
# Regenerate: gnome-settings-dump

[/]
action-middle-click-titlebar='lower'
button-layout='icon,menu:minimize,maximize,close'
resize-with-right-button=true
