# dconf-branch: /org/gnome/desktop/notifications/
# Regenerate: gnome-settings-dump

[/]
application-children=['gnome-about-panel', 'zen', 'discord', 'signal', 'org-gnome-extensions', 'codium', 'gnome-power-panel']
show-banners=false

[application/codium]
application-id='codium.desktop'

[application/discord]
application-id='discord.desktop'

[application/gnome-about-panel]
application-id='gnome-about-panel.desktop'

[application/gnome-power-panel]
application-id='gnome-power-panel.desktop'

[application/org-gnome-extensions]
application-id='org.gnome.Extensions.desktop'

[application/signal]
application-id='signal.desktop'

[application/zen]
application-id='zen.desktop'
