# dconf-branch: /org/gnome/desktop/interface/
# Regenerate: gnome-settings-dump

[/]
color-scheme='prefer-dark'
cursor-blink=true
cursor-blink-time=1200
cursor-size=0
cursor-theme=''
document-font-name='Noto Sans  10'
enable-hot-corners=false
font-antialiasing='rgba'
font-hinting='full'
font-name='Sans 10'
gtk-key-theme=''
gtk-theme='Adwaita'
icon-theme='elementary'
monospace-font-name='Hack  10'
scaling-factor=uint32 1
text-scaling-factor=1.0
toolbar-style='text'
