# dconf-branch: /org/gnome/desktop/peripherals/
# Regenerate: gnome-settings-dump

[keyboard]
numlock-state=true

[mouse]
double-click=400
drag-threshold=8

[touchpad]
two-finger-scrolling-enabled=true
