# dconf-branch: /org/gnome/settings-daemon/plugins/media-keys/
# Regenerate: gnome-settings-dump

[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']

[custom-keybindings/custom0]
binding='<Super>Return'
command='kitty'
name='Terminal'
