# dconf-branch: /org/gnome/desktop/notifications/
# Regenerate: gnome-settings-dump

[/]
application-children=['gnome-about-panel', 'zen']
show-banners=false

[application/gnome-about-panel]
application-id='gnome-about-panel.desktop'

[application/zen]
application-id='zen.desktop'
