[color]
; Catppuccin Mocha
background  = #1e1e2e
foreground  = #cdd6f4
transparent = #00000066

black   = #45475a
red     = #f38ba8
green   = #a6e3a1
yellow  = #f9e2af
blue    = #89b4fa
purple  = #cba6f7
cyan    = #89dceb
white   = #bac2de
orange  = #fab387
pink    = #f5c2e7
